server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
